# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

jobs:
- job: Windows
  pool:
   # vmImage: 'ubuntu-latest'
    vmImage: 'windows-latest' 
  steps:
  - script: echo hello from Windows

variables:
  phpVersion: 7.2
  # the name of the service connection that you created above
  serviceConnectionToAzure: 120072521000202
  # the name of your web app here is the same one you used above
  # when you created the web app using the Azure CLI
  appName: meredith-120072521000202





- task: ArchiveFiles@1
  displayName: Archive files
  inputs:
    rootFolder: $(System.DefaultWorkingDirectory)
    includeRootFolder: false
    archiveType: zip

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)


- task: AzureRmWebAppDeployment@4
  displayName: Azure Web App Deploy
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '120072521000202'
    appType: 'webApp'
    WebAppName: 'meredith-120072521000202'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    enableCustomDeployment: true
    DeploymentType: 'runFromZip'
